/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Block: typeof import('./../components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./../components/breadcrumb/index.vue')['default']
    Chart: typeof import('./../components/chart/index.vue')['default']
    DensityDropdown: typeof import('./../components/density-dropdown/index.vue')['default']
    Footer: typeof import('./../components/footer/index.vue')['default']
    FormWrapper: typeof import('./../components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./../components/global-setting/index.vue')['default']
    List: typeof import('./../components/message-box/list.vue')['default']
    Menu: typeof import('./../components/menu/index.vue')['default']
    MessageBox: typeof import('./../components/message-box/index.vue')['default']
    Navbar: typeof import('./../components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/tab-bar/index.vue')['default']
    TabItem: typeof import('./../components/tab-bar/tab-item.vue')['default']
    UserList: typeof import('./../components/ZsSelectUser/components/user-list.vue')['default']
    UserSelected: typeof import('./../components/ZsSelectUser/components/user-selected.vue')['default']
    ZsAvatar: typeof import('./../components/zs-avatar/index.vue')['default']
    ZsBreadcrumb: typeof import('./../components/zs-breadcrumb/index.vue')['default']
    ZsContainer: typeof import('./../components/zs-container/index.vue')['default']
    ZsDept: typeof import('./../components/zs-dept/index.vue')['default']
    ZsEditor: typeof import('./../components/zs-editor/index.vue')['default']
    ZsFilesList: typeof import('./../components/zs-files-list/index.vue')['default']
    ZsGap: typeof import('./../components/zs-gap/index.vue')['default']
    ZsIcon: typeof import('./../components/zs-icon/index.vue')['default']
    ZsScetion: typeof import('./../components/zs-scetion/index.vue')['default']
    ZsSelectedIcon: typeof import('./../components/zs-selected-icon/index.vue')['default']
    ZsSelectUser: typeof import('./../components/ZsSelectUser/index.vue')['default']
    ZsStatus: typeof import('./../components/zs-status/index.vue')['default']
    ZsUploadFiles: typeof import('./../components/zs-upload-files/index.vue')['default']
    ZsUploadImage: typeof import('./../components/zs-upload-image/index.vue')['default']
  }
}
